name: vegnbio_front
description: Application Flutter pour VegnBio présentant l'entreprise et ses horaires.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  http: ^1.1.0
  flutter_riverpod: ^2.4.9
  image_picker: ^1.0.4
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/playstore.png"  # Icône spécifique pour Android
  image_path_ios: "assets/icon/appstore.png"      # Icône spécifique pour iOS
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/web.jpg"            # Icône spécifique pour le web
    background_color: "#ffffff"
    theme_color: "#ffffff"